### ISSUE TITLE
Clarify essen

### ISSUE THREAD

**Issue by christian-weiss** [Freifunk-Hamm/ffapi#23]
Website:
https://freifunk-essen.de/

Suggested changes:

1. :heavy_check_mark: 3 node lists. 1 is down and should be deleted: http://map.freifunk-ruhrgebiet.de/data/nodes.json
2. :heavy_check_mark: remove google+ from contact (service is no longer offered by google)
3. :heavy_check_mark: delete or update meta community (as Freifunk Ruhrgebiet is no longer existing)
4. :heavy_check_mark: drop state.nodes or automate file update (host it on your webserver or on your own git hub repo)
5. :heavy_check_mark: update state.lastchange
6. :heavy_check_mark: delete or change "feeds" URL (=> is ok as it is, but has no events at the moment)
7. :heavy_check_mark: techdetails.firmware.url
8. :heavy_check_mark: check and update techdetails.networks and techdetails.dns
9. :heavy_check_mark: update to schema 0.4.16
10. :heavy_check_mark: This crowdfunding campagne is outdated. I think it should be dropped from API file:
https://api.betterplace.org/de/api_v4/projects/34173.json
closed in 2016, Essen (=> deleted from file)
11. :heavy_check_mark: Please verify if you still want to campagne for Freifunk Rheinland:
https://api.betterplace.org/de/api_v4/projects/16049.json
12. :heavy_check_mark: Please confirm that your supporter is "Freifunk Rheinland e.V.". 
(I guess Freifunk Essen e.V. is now the supporter of this community)

**Comment by christian-weiss** [comment]
Email to community was send by today (asked for feedback about PR / help).

**Comment by christian-weiss** [comment]
May relate to: https://github.com/Freifunk-Hamm/ffapi/issues/24

**Comment by christian-weiss** [comment]
Email was not delivered:
```
Hi. This is the qmail-send program at alioth.uberspace.de.
I'm afraid I wasn't able to deliver your message to the following addresses.
This is a permanent error; I've given up. Sorry it didn't work out.

<kontakt@freifunk-essen.de>:
Zend OPcache requires Zend Engine API version 220131226.
The Zend Engine API version 220100525 which is installed, is outdated.
/PHP Fatal error:  Out of memory (allocated 15466496) (tried to allocate 576 bytes) in /var/www/virtual/ffessen/ticket.freifunk-essen.de/include/mysqli.php on line 192
I'm not going to try again; this message has been in the queue too long.

--- Below this line is a copy of the message.
...
```

looks like the incomming e-mail is process by a ticket system (written in PHP) which failed with a OOM-error.

**Comment by christian-weiss** [comment]
When i try to send a message via contact form, then there is no visual feedback, that the message was send - i think the contact form is also on error.
https://freifunk-essen.de/kontakt#abgesendet

**Comment by christian-weiss** [comment]
I left a message on their mailbox +49-211-41741221

**Comment by christian-weiss** [comment]
I also send an email to press/media contact.

**Comment by christian-weiss** [comment]
Last github commit in FFessen github organisation is 2 years old (2019).
https://github.com/FFEssen/site-ffe

**Comment by christian-weiss** [comment]
Now trying to get contact to someone from Freifunk Essen via freifunk.slack.com channel: #essen ....

**Comment by christian-weiss** [comment]
No response so far. Asked again via slack. Hope to get feedback soon...

**Comment by christian-weiss** [comment]
Telegram chat:
I tried to contact Freifunk Essen via Telegram group of Freifunk Essen on 21th of may.
This group was closed that day by intervention of Erik Schauer (PR/Media contact person of Freifunk Essen).

Slack (Freifunk, Channel #essen):
I asked again on 2021-07-05 (7 days ago), still no feedback.

E-Mail (kontakt@)
Mail was re-send today. I hope the mailserver was fixed in between.

Github:
I filed an github issue today: https://github.com/FFEssen/supernode-ansible/issues/3

**Comment by christian-weiss** [comment]
E-Mail (kontakt@):
Still broken. 

Forum:
In response to https://forum.freifunk.net/t/map-freifunk-essen-de-funktioniert-nicht-mehr/22911 i asked Anton to forward my issue to "someone from Freifunk Essen". => it was forwarded.

**Comment by pberndro** [comment]
@christian-weiss 

1.
pls use "https://map.freifunk-essen.de/data/nodes.json"

2.
ok

3.
please remove, we still have no meta community.

4,5,6,7,8,9
ok

10.
there will be a new campagne in the future, we will inform you if the link is public.

11.
yes until we have our own campagne.

12.
Freifunk Essen e.V. is correct and the legal entity for the Freifunk Essen Community.

Sorry for the email problems and delay, we are working together the provider to fix.

Kind regards,
Philip (chairman Freifunk Essen e.V.)

**Comment by christian-weiss** [comment]
@pberndro thanks for contribution.

There is an issue with your URL https://map.freifunk-essen.de/data/nodes.json
(Certificate issue) 
![Screenshot from 2021-07-29 22-12-59](https://user-images.githubusercontent.com/1694741/127559675-37520a54-d526-4ec0-9d73-875cf29acf72.png)

**Comment by christian-weiss** [comment]
Ok, i updated essen.json accordingly (except your new URL, as it has a certificate issue).

@pberndro To improve the autonomy of Freifunk Essen i suggest to not depend on Freifunk Hamm Github Repo for hosting your API file.
Feel free to host https://github.com/Freifunk-Hamm/ffapi/blob/master/essen.json on Freifunk Essen Github Repo or on your webserver and then create a pull request to update the reference to it (URL) in https://github.com/freifunk/directory.api.freifunk.net/blob/59f694edb9c4239c67e9046d722c3e5897b486db/directory.json#L91 - or ping me an i will take care of that PR.

**Comment by pberndro** [comment]
>Ok, i updated essen.json accordingly (except your new URL, as it has a certificate issue).

Thanks for feedback, fixed on our site.

>To improve the autonomy of Freifunk Essen i suggest to not depend on Freifunk Hamm Github Repo for hosting your API file.

god point to move the api file: done :-)
https://raw.githubusercontent.com/FFEssen/ffapi/main/essen.json

Thanks @christian-weiss for your support!

**Comment by christian-weiss** [comment]
@pberndro thanks for your feedback.
I will ensure that API directory entry for essen will be pointing to https://raw.githubusercontent.com/FFEssen/ffapi/main/essen.json
after merge of my PR i will drop essen.json from this repo.

**Comment by christian-weiss** [comment]
PR is merged.
